CREATE TABLE FIREEMBLEM.FARM (
ID NUMBER(11) -- IDPRIMARYKEY
,LOCATION VARCHAR2(30) NOT NULL -- 位置UNIQUE
,PARENT_FARM NUMBER(3) NOT NULL -- 父田UNIQUE
,INDEX_NUM NUMBER(3) NOT NULL -- 编号UNIQUE
,CROP_ID VARCHAR2(100) -- 作物ID
,CROP_NM VARCHAR2(1) DEFAULT '0' -- 作物名
,CROP_HP NUMBER(4) DEFAULT 0 -- 作物HP
,CROP_PRICE NUMBER(5) DEFAULT 0 -- 售价
,START_DATE VARCHAR2(4) DEFAULT 0 -- 种植日期
,TOTAL_LEVEL NUMBER(3,1) DEFAULT 0 -- 土地等级
,SIZE_LEVEL NUMBER(3,1) DEFAULT 0 -- 大小等级
,SPEED_LEVEL NUMBER(3,1) DEFAULT 0 -- 速度等级
,QUALITY_LEVEL NUMBER(3,1) DEFAULT 0 -- 质量等级
,COUNT_LEVEL NUMBER(3,1) DEFAULT 0 -- 数量等级
,HEALTH NUMBER(3) DEFAULT 0 -- 健康度
PRIMARY KEY(ID));
