CREATE TABLE fireemblem.hero (
ID NUMBER(11) -- IDPRIMARYKEY
,MASTER_ID NUMBER(11) NOT NULL -- 关联主表主键
,TITLE_NAME VARCHAR2(40) -- 称号UNIQUE
,NAME VARCHAR2(40) -- 名UNIQUE
,NICK_NAME VARCHAR2(40) -- 昵称
,IMG_NAME VARCHAR2(50) NOT NULL -- 立绘图片文件夹名
,ORIGIN VARCHAR2(40) NOT NULL -- 角色作品
,HP NUMBER(3) DEFAULT 0 -- 生命值
,ATTACT NUMBER(3) DEFAULT 0 -- 攻击
,SPEED NUMBER(3) DEFAULT 0 -- 速度
,DEF NUMBER(3) DEFAULT 0 -- 防御
,MDF NUMBER(3) DEFAULT 0 -- 魔防
,WEAPON VARCHAR2(40) -- 武器名
,SKILL_A VARCHAR2(40) -- A技能
,SKILL_B VARCHAR2(40) -- B技能
,SKILL_C VARCHAR2(40) -- C技能
,SKILL_D VARCHAR2(40) -- 圣印技能
,SKILL_S VARCHAR2(40) -- 支援技能
,SKILL_E VARCHAR2(40) -- 必杀技能
,LIMIT_PLUS NUMBER(2) DEFAULT 0 -- 突破极限
,DRAGON_FLOWER NUMBER(2) DEFAULT 0 -- 神龙之花
,SUPPORT_MATE NUMBER(11) -- 支援对象
,BLESSING VARCHAR2(3) -- 祝福
,MOVE_TYPE VARCHAR2(2) NOT NULL -- 兵种
,WEAPON_TYPE VARCHAR2(3) NOT NULL -- 武器类型
,COLOR VARCHAR2(3) NOT NULL -- 宝珠颜色
,RACE VARCHAR2(3) -- 种族
,HERO_TYPE VARCHAR2(3) -- 英雄类型(连翼/传承)
,TEAM NUMBER(2) -- 队伍
,SKILL_POINT NUMBER(5) DEFAULT 0 -- 技能点
,HERO_POINT NUMBER(5) DEFAULT 0 -- 英雄点
,SPEC_TAG VARCHAR2(30) -- 特效标签
,POOL VARCHAR2(30) -- 卡池
,FAVORITE VARCHAR2(2) -- 喜欢
,RANK VARCHAR2(1) -- 评价等级
,CREATE_DATETIME TIMESTAMP -- 登录日期
,UPDATE_DATETIME TIMESTAMP -- 更新日期
PRIMARY KEY(ID));