CREATE TABLE "FIREEMBLEM"."HERO_MASTER" (
"ID" NUMBER(11) NOT NULL ENABLE, --PRIMARYKEY
"ORIGIN_ID" VARCHAR2(30) NOT NULL ENABLE, --作品IDEXISTCOL
"ORIGIN_NAME" VARCHAR2(30) NOT NULL ENABLE, --作品名
"NAME" VARCHAR2(30) NOT NULL ENABLE, --人物名EXISTCOL
PRIMARY KEY ("ID"));