CREATE TABLE "FIREEMBLEM"."HERO" (
"ID" VARCHAR2(11) NOT NULL ENABLE, --PRIMARYKEY
"MASTER_ID" VARCHAR2(11) NOT NULL ENABLE, --关联主表主键
"TITLE_NAME" VARCHAR2(30) NOT NULL ENABLE, --称号
"NAME" VARCHAR2(30) NOT NULL ENABLE, --角色名
"NICK_NAME" VARCHAR2(60) DEFAULT NULL, --昵称
"IMG_NAME" VARCHAR2(150) DEFAULT NULL, --立绘图片文件夹名
"ORIGIN" VARCHAR2(30) DEFAULT NULL, --角色作品
"HP" NUMBER(11) DEFAULT NULL, --生命值
"ATTACT" NUMBER(11) DEFAULT NULL, --攻击
"SPEED" NUMBER(11) DEFAULT NULL, --速度
"DEF" NUMBER(11) DEFAULT NULL, --防御
"MDF" NUMBER(11) DEFAULT NULL, --魔防
"WEAPON" VARCHAR2(30) DEFAULT NULL, --武器名
"SKILL_A" VARCHAR2(30) DEFAULT NULL, --A技能
"SKILL_B" VARCHAR2(30) DEFAULT NULL, --B技能
"SKILL_C" VARCHAR2(30) DEFAULT NULL, --C技能
"SKILL_D" VARCHAR2(30) DEFAULT NULL, --圣印技能
"SKILL_S" VARCHAR2(30) DEFAULT NULL, --支援技能
"SKILL_E" VARCHAR2(30) DEFAULT NULL, --必杀技能
"LIMIT_PLUS" NUMBER(11) DEFAULT NULL, --突破极限
"SUPPORT_MATE" VARCHAR2(11) DEFAULT NULL, --支援对象
"BLESSING" VARCHAR2(2) DEFAULT NULL, --祝福
"MOVE_TYPE" VARCHAR2(2) DEFAULT NULL, --兵种
"WEAPON_TYPE" VARCHAR2(2) DEFAULT NULL, --武器类型
"COLOR" VARCHAR2(2) DEFAULT NULL, --宝珠颜色
"RACE" VARCHAR2(2) DEFAULT NULL, --种族
"HERO_TYPE" VARCHAR2(2) DEFAULT NULL, --英雄类型
"TEAM" NUMBER(2) DEFAULT NULL, --队伍
"SKILL_POINT" NUMBER(2) DEFAULT NULL, --技能点
"HERO_POINT" NUMBER(2) DEFAULT NULL, --英雄点
"SPEC_TAG" VARCHAR2(30) DEFAULT NULL, --特效标签
"POOL" VARCHAR2(30) DEFAULT NULL, --卡池
"CREATE_DATETIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --登录日期
"UPDATE_DATETIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --更新日期
PRIMARY KEY ("ID"));