CREATE TABLE "FIREEMBLEM"."HERO_CONTENT" (
"ID" NUMBER(11) NOT NULL ENABLE, --PRIMARYKEY
"CATEGORY_ID" VARCHAR2(11) NOT NULL ENABLE, --類別EXISTCOL
"CATEGORY_NAME" VARCHAR2(11) NOT NULL ENABLE, --類別名
"CODE_ID" VARCHAR2(11) NOT NULL ENABLE, --codeIdEXISTCOL
"CODE_NAME" VARCHAR2(11) NOT NULL ENABLE, --code名
"IMG_SRC" VARCHAR2(80) DEFAULT NULL, --图片路径
"NAME_EXPAND1" VARCHAR2(50) DEFAULT NULL, --扩展字段1
"NAME_EXPAND2" VARCHAR2(50) DEFAULT NULL, --扩展字段2
"NAME_EXPAND3" VARCHAR2(50) DEFAULT NULL, --扩展字段3
PRIMARY KEY ("ID"));