CREATE TABLE FIREEMBLEM.HERO_CONTENT (
ID NUMBER(11) -- IDPRIMARYKEY
,CATEGORY_ID VARCHAR2(11) NOT NULL -- 类别UNIQUE
,CATEGORY_NAME VARCHAR2(30) -- 类别名
,CODE_ID VARCHAR2(11) NOT NULL -- CODEUNIQUE
,CODE_NAME VARCHAR2(30) -- CODE名
,IMG_SRC VARCHAR2(80) DEFAULT null -- 图片名
,NAME_EXPAND1 VARCHAR2(50) DEFAULT null -- 扩展1
,NAME_EXPAND2 VARCHAR2(50) DEFAULT null -- 扩展2
,NAME_EXPAND3 VARCHAR2(50) DEFAULT null -- 扩展3
,NAME_EXPAND4 VARCHAR2(50) DEFAULT null -- 扩展4
,NAME_EXPAND5 VARCHAR2(50) DEFAULT null -- 扩展5
,NAME_EXPAND6 VARCHAR2(50) DEFAULT null -- 扩展6
,NAME_EXPAND7 VARCHAR2(50) DEFAULT null -- 扩展7
,NAME_EXPAND8 VARCHAR2(50) DEFAULT null -- 扩展8
,NAME_EXPAND9 VARCHAR2(50) DEFAULT null -- 扩展9
PRIMARY KEY(ID));
