CREATE TABLE "FIREEMBLEM"."HERO_MASTER" (
"ID" NUMBER(11) NOT NULL ENABLE, --PRIMARYKEY
"NAME" VARCHAR2(11) NOT NULL ENABLE, --关联主表主键EXISTCOL
"ORIGIN" VARCHAR2(30) NOT NULL ENABLE, --称号EXISTCOL
"EXPAND_COL1" VARCHAR2(30) DEFAULT NULL, --扩展字段1
"EXPAND_COL2" VARCHAR2(30) DEFAULT NULL, --扩展字段2
"EXPAND_COL3" VARCHAR2(30) DEFAULT NULL, --扩展字段3
PRIMARY KEY ("ID"));