CREATE TABLE FIREEMBLEM.RECIPE (
ID NUMBER(11) NOT NULL -- IDPRIMARYKEY
,CATEGORY_MAIN VARCHAR2(11) NOT NULL -- 大分类UNIQUE
,CATEGORY_SUB VARCHAR2(50) NOT NULL -- 小分类UNIQUE
,NAME VARCHAR2(50) NOT NULL -- 名称UNIQUE
,PRICE NUMBER(15,1) -- 售价
,SKILL_LEVEL NUMBER(3) -- 技能等级
,RECIPE1 VARCHAR2(50) -- 材料1
,RECIPE2 VARCHAR2(50) -- 材料2
,RECIPE3 VARCHAR2(50) -- 材料3
,RECIPE4 VARCHAR2(50) -- 材料4
,RECIPE5 VARCHAR2(50) -- 材料5
,RECIPE6 VARCHAR2(50) -- 材料6
,PRIMARY KEY(ID));
