CREATE TABLE fireemblem.servant (
ID VARCHAR2(4) -- IDPRIMARYKEY
,IMG_NAME VARCHAR2(50) NOT NULL -- 立绘图片文件夹名UNIQUE
,NAME VARCHAR2(40) -- 名
,NICK_NAME VARCHAR2(40) -- 昵称
,CLASS_TYPE VARCHAR2(2) NOT NULL -- 兵种
,HERO_TYPE VARCHAR2(2) -- 从者类型(拐,打手)
,EVENT_FLAG VARCHAR2(1) -- 活动从者
,HP NUMBER(5) DEFAULT 0 -- 生命值
,ATTACT NUMBER(5) DEFAULT 0 -- 攻击
,SKILL_1 VARCHAR2(40) -- 1技能
,SKILL_2 VARCHAR2(40) -- 2技能
,SKILL_3 VARCHAR2(40) -- 3技能
,SKILL_EXTRA VARCHAR2(40) -- 宝具名
,EXTRA_TYPE VARCHAR2(2) -- 宝具类型(单体,全体)
,EXTRA_COLOR VARCHAR2(3) NOT NULL -- 宝具颜色
,LIMIT NUMBER(2) DEFAULT 0 -- 突破极限
,TRAITS VARCHAR2(3) -- 特性
,TEAM NUMBER(2) -- 队伍
,FAVORITE VARCHAR2(2) -- 喜欢
,RANK VARCHAR2(1) -- 评价等级
,CREATE_DATETIME TIMESTAMP DEFAULT SYS_DATE -- 登录日期
,UPDATE_DATETIME TIMESTAMP DEFAULT SYS_DATE -- 更新日期
PRIMARY KEY(ID));
