CREATE TABLE "FIREEMBLEM"."SKILL_INFO" (
"ID" NUMBER(11) NOT NULL ENABLE, --PRIMARYKEY
"NAME" VARCHAR2(11) NOT NULL ENABLE, --技能名EXISTCOL
"TYPE" VARCHAR2(30) NOT NULL ENABLE, --类别EXISTCOL
"EXTEND" VARCHAR2(30) DEFAULT NULL, --继承
"INFO" VARCHAR2(30) DEFAULT NULL, --描述
"WEAPON_POWER" VARCHAR2(30) DEFAULT NULL, --武器威力
"EFFECTS" VARCHAR2(30) DEFAULT NULL, --特殊效果
PRIMARY KEY ("ID"));