CREATE TABLE fireemblem.skill (
ID NUMBER(11) -- IDPRIMARYKEY
,NAME VARCHAR2(30) NOT NULL -- 技能名UNIQUE
,TYPE VARCHAR2(1) NOT NULL -- 技能类型UNIQUE
,INFO VARCHAR2(100) -- 介绍
,EXTEND_FLAG VARCHAR2(1) DEFAULT '0' -- 继承
,POWER NUMBER(2) DEFAULT 0 -- 武器威力
,HP_PLUS NUMBER(2) DEFAULT 0 -- HP加成
,POW_PLUS NUMBER(2) DEFAULT 0 -- POW加成
,SPD_PLUS NUMBER(2) DEFAULT 0 -- SPD加成
,DEF_PLUS NUMBER(2) DEFAULT 0 -- DEF加成
,MDF_PLUS NUMBER(2) DEFAULT 0 -- MDF加成
,HP_BUFF NUMBER(2) DEFAULT 0 -- HP增益
,POW_BUFF NUMBER(2) DEFAULT 0 -- POW增益
,SPD_BUFF NUMBER(2) DEFAULT 0 -- SPD增益
,DEF_BUFF NUMBER(2) DEFAULT 0 -- DEF增益
,MDF_BUFF NUMBER(2) DEFAULT 0 -- MDF增益
,HP_DEBUFF NUMBER(2) DEFAULT 0 -- HP减益
,POW_DEBUFF NUMBER(2) DEFAULT 0 -- POW减益
,SPD_DEBUFF NUMBER(2) DEFAULT 0 -- SPD减益
,DEF_DEBUFF NUMBER(2) DEFAULT 0 -- DEF减益
,MDF_DEBUFF NUMBER(2) DEFAULT 0 -- MDF减益
PRIMARY KEY(ID));
